[package]
name = "lampvm-toolchain"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.228", features = ["derive"]}
serde_yaml = "0.9.34"
once_cell = "1.21.3"
clap = { version = "4.5.54", features = ["derive"] }